In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
s="./image_data/"
files=os.listdir(s)
files

['0-10.bmp',
 '0-2.bmp',
 '0-3.bmp',
 '0-4.bmp',
 '0-5.bmp',
 '0-6.bmp',
 '0-8.bmp',
 '0-9.bmp',
 '1-1.bmp',
 '1-10.bmp',
 '1-2.bmp',
 '1-3.bmp',
 '1-4.bmp',
 '1-6.bmp',
 '1-8.bmp',
 '1-9.bmp',
 '2-1.bmp',
 '2-10.bmp',
 '2-3.bmp',
 '2-4.bmp',
 '2-5.bmp',
 '2-6.bmp',
 '2-7.bmp',
 '2-8.bmp',
 '2-9.bmp',
 '3-1.bmp',
 '3-10.bmp',
 '3-3.bmp',
 '3-4.bmp',
 '3-5.bmp',
 '3-6.bmp',
 '3-7.bmp',
 '3-8.bmp',
 '3-9.bmp',
 '4-1.bmp',
 '4-2.bmp',
 '4-4.bmp',
 '4-6.bmp',
 '4-8.bmp',
 '4-9.bmp',
 '5-1.bmp',
 '5-10.bmp',
 '5-2.bmp',
 '5-3.bmp',
 '5-6.bmp',
 '5-7.bmp',
 '5-9.bmp',
 '6-1.bmp',
 '6-10.bmp',
 '6-2.bmp',
 '6-3.bmp',
 '6-4.bmp',
 '6-6.bmp',
 '6-8.bmp',
 '6-9.bmp',
 '7-10.bmp',
 '7-2.bmp',
 '7-3.bmp',
 '7-5.bmp',
 '7-6.bmp',
 '7-7.bmp',
 '7-9.bmp',
 '8-1.bmp',
 '8-10.bmp',
 '8-2.bmp',
 '8-3.bmp',
 '8-4.bmp',
 '8-5.bmp',
 '8-6.bmp',
 '8-8.bmp',
 '8-9.bmp',
 '9-1.bmp',
 '9-2.bmp',
 '9-3.bmp',
 '9-4.bmp',
 '9-5.bmp',
 '9-6.bmp',
 '9-8.bmp',
 '9-9.bmp',
 'img_0-1.bmp',
 'img_0-7.bmp',
 'img_1-5.bm

In [3]:
num=100 #number of sample
row=240 #number of row
col=240 #number of column
images = np.zeros((num,row,col)) 

In [4]:
n=0
for pic in files:
    images[n,:,:]=cv2.imread(s+str(pic),0)
    n=n+1
    
print(images.shape)  

(100, 240, 240)


In [5]:
feature = np.zeros((num,round(row/40),round(col/40))) 
for ni in range(0,num):
    for nr in range(0,row):
        for nc in range(0,col):
            if images[ni,nr,nc]==0:
                feature[ni,int(nr/40),int(nc/40)]+=1

dataset = feature[:,:].reshape(-1,round(row/40)*round(col/40)).astype(np.float32) 


In [6]:
import re

regex01=r"[0-9](?=-)"
names=re.findall(regex01,str(files))
labels = np.asarray(names)

In [7]:
print(dataset.shape)
print(labels.shape)
print(labels)

(100, 36)
(100,)
['0' '0' '0' '0' '0' '0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '2' '2'
 '2' '2' '2' '2' '2' '2' '2' '3' '3' '3' '3' '3' '3' '3' '3' '3' '4' '4'
 '4' '4' '4' '4' '5' '5' '5' '5' '5' '5' '5' '6' '6' '6' '6' '6' '6' '6'
 '6' '7' '7' '7' '7' '7' '7' '7' '8' '8' '8' '8' '8' '8' '8' '8' '8' '9'
 '9' '9' '9' '9' '9' '9' '9' '0' '0' '1' '1' '2' '3' '4' '4' '4' '4' '5'
 '5' '5' '6' '6' '7' '7' '7' '8' '9' '9']


In [8]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3)
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)
print(y_train)

(70, 36)
(70,)
(30, 36)
(30,)
['2' '3' '4' '8' '4' '9' '3' '1' '0' '5' '6' '9' '9' '6' '7' '8' '5' '7'
 '0' '0' '3' '6' '8' '7' '0' '5' '8' '6' '5' '0' '8' '1' '3' '9' '2' '1'
 '5' '1' '7' '3' '7' '7' '2' '2' '0' '8' '5' '8' '2' '4' '6' '4' '1' '8'
 '9' '1' '3' '2' '8' '4' '7' '1' '3' '9' '2' '5' '7' '3' '0' '3']


In [9]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model = neighbors.KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)


X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print(y_test)
print(y_pred)
print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('confusion matrix: {}'.format(con_matrix))

['6' '0' '9' '6' '8' '4' '7' '2' '1' '5' '6' '9' '6' '3' '7' '4' '0' '2'
 '9' '4' '4' '5' '1' '5' '4' '2' '9' '1' '0' '6']
['6' '0' '7' '5' '8' '4' '7' '2' '1' '5' '6' '9' '5' '3' '7' '4' '0' '2'
 '9' '4' '4' '3' '1' '5' '1' '2' '7' '1' '0' '6']
number of correct sample: 24
accuracy: 0.8
confusion matrix: [[3 0 0 0 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 4 0 0 0 0 0]
 [0 0 0 1 0 2 0 0 0 0]
 [0 0 0 0 0 2 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 2 0 2]]
